# using loops

In [6]:
%matplotlib inline
import cv2
import numpy as np 
from matplotlib import pyplot as plt

img = cv2.imread(r"C:\Users\Mrunal\Documents\CoE\LECTURES\IVP LAB\DIP3E_Original_Images_CH03\Fig0333(a)(test_pattern_blurring_orig).tif", 0)
# print(img.dtype)
cv2.imshow("input image", img)
print(img.shape)
cv2.waitKey(0)
# cv2.destroyAllWindows()

m, n = img.shape 

# Develop Averaging filter(3, 3) mask 
mask = np.ones([3, 3], dtype = np.uint8) 
mask = mask / 9

# Convolve the 3X3 mask over the image 
img_new = np.zeros([m, n], dtype = np.uint8) 

for i in range(1, m-1): 
    for j in range(1, n-1): 
        temp = img[i-1, j-1]*mask[0, 0]+img[i-1, j]*mask[0, 1]+img[i-1, j + 1]*mask[0, 2]+img[i, j-1]*mask[1, 0]+ img[i, j]*mask[1, 1]+img[i, j + 1]*mask[1, 2]+img[i + 1, j-1]*mask[2, 0]+img[i + 1, j]*mask[2, 1]+img[i + 1, j + 1]*mask[2, 2] 
        img_new[i, j] = np.uint8(temp) 

img_blur = img_new.astype(np.uint8) 
print(img_blur.shape)
cv2.imshow("blurred image 3x3", img_blur)
cv2.waitKey(0)
cv2.destroyAllWindows()

(500, 500)
(500, 500)


In [27]:
# for example only, slicing
img_tp = np.zeros([4, 4], dtype = np.uint8) 
print(img_tp)
img_tp[1:-1, 1:-1]

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


array([[0, 0],
       [0, 0]], dtype=uint8)

# cv2 functions

In [7]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

img = cv2.imread(r'C:\Users\Mrunal\Documents\CoE\LECTURES\IVP LAB\DIP3E_Original_Images_CH03\Fig0333(a)(test_pattern_blurring_orig).tif')
print(img.shape)
cv2.imshow("input image", img)
cv2.waitKey(0)

kernel = np.ones((5,5),np.float32)/25
dst = cv2.filter2D(img,-1,kernel)   # -1 for output depth same as input
print(dst.shape)
cv2.imshow("output image", dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

(500, 500, 3)
(500, 500, 3)


In [8]:
# kernel as a parameter
import cv2
import numpy as np
from matplotlib import pyplot as plt

img = cv2.imread(r'C:\Users\Mrunal\Documents\CoE\LECTURES\IVP LAB\DIP3E_Original_Images_CH03\Fig0333(a)(test_pattern_blurring_orig).tif')

blur = cv2.blur(img,(11, 11))

print(blur.shape)
cv2.imshow("output image", blur)
cv2.waitKey(0)
cv2.destroyAllWindows()

(500, 500, 3)


# HW

In [ ]:
Try 5X5 without opencv and compare it with opencv

# RESOURCES

In [ ]:
# https://www.geeksforgeeks.org/spatial-filters-averaging-filter-and-median-filter-in-image-processing/
# https://www.geeksforgeeks.org/cnn-introduction-to-padding/
# https://docs.opencv.org/master/d2/de8/group__core__array.html#ga209f2f4869e304c82d07739337eae7c5